routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// THROTTLES
$throttle_15 = 'GrahamCampbell\Throttle\Http\Middleware\ThrottleMiddleware:5,15';
$throttle_60 = 'GrahamCampbell\Throttle\Http\Middleware\ThrottleMiddleware:5,60';


// PAGES
Route::get('/', 'PageController@home')
	->name('page.home');

Route::get('/how-it-works', 'PageController@howItWorks')
	->name('page.howItWorks');

Route::get('/faq', 'PageController@faq')
	->name('page.faq');

Route::get('/privacy', 'PageController@privacy')
	->name('page.privacy');

Route::get('/terms', 'PageController@terms')
	->name('page.terms');


// MY
Route::get('/my-lessons', 'LessonController@myLessons')
	->name('lesson.myLessons');

Route::get('/my-subscriptions', 'SubscriptionController@mySubscriptions')
	->name('subscription.mySubscriptions');

Route::get('/my-profile', 'UserController@myProfile')
	->name('user.myProfile');

Route::get('/my-account', 'UserController@myAccount')
	->name('user.myAccount');

// ADMIN
Route::get('/admin', 'AdminController@home')
	->name('admin.home');

Route::get('/admin/users', 'AdminController@users')
	->name('admin.users');

Route::get('/admin/lessons', 'AdminController@lessons')
	->name('admin.lessons');

Route::get('/admin/subscriptions', 'AdminController@subscriptions')
	->name('admin.subscriptions');

Route::get('/admin/find', 'AdminController@find')
	->name('admin.find');

// USERS

Route::get('/users/{user}', 'UserController@show')
	->name('user.show');

Route::get('/users/{user}/edit', 'UserController@edit')
	->name('user.edit');

Route::get('/users/{user}/profile/edit', 'UserController@editProfile')
	->name('user.editProfile');

Route::get('/users/{user}/payouts/edit', 'UserController@editPayoutDetails')
	->name('user.editPayoutDetails');

Route::get('/users/{user}/payoff', 'UserController@showPayOff')
	->name('user.showPayOff');

Route::get('/users/{user}/payouts', 'UserController@showPayouts')
	->name('user.showPayouts');

Route::get('/users/{user}/upgrade-to-teacher', 'UserController@showUpgradeToRegisteredTeacher')
	->name('user.showUpgradeToRegisteredTeacher');

Route::get('/users/{user}/become-a-tutor-or-teacher', 'UserController@showBecomeATeacher')
	->name('user.showBecomeATeacher');

Route::get('/users/{user}/profile/edit', 'UserController@editProfile')
	->name('user.editProfile');

Route::patch('/users/{user}', 'UserController@update')
	->name('user.update');

Route::patch('/users/{user}/profile', 'UserController@updateProfile')
	->name('user.updateProfile');

Route::patch('/users/{user}/payout', 'UserController@updatePayoutDetails')
	->name('user.updatePayoutDetails');

Route::post('/users/{user}/payoff', 'UserController@payOff')
	->name('user.payOff');

Route::post('/users/{user}/upgrade', 'UserController@upgrade')
	->name('user.upgrade');

Route::post('/users/{user}/upgrade/cancel', 'UserController@cancelUpgrade')
	->name('user.cancelUpgrade');

Route::post('/users/{user}/downgrade', 'UserController@downgrade')
	->name('user.downgrade');

Route::post('/users/{user}/become-a-tutor-teacher', 'UserController@becomeATeacher')
	->name('user.becomeATeacher');

Route::post('/users/{user}/upgrade-to-teacher', 'UserController@upgradeToRegisteredTeacher')
	->name('user.upgradeToRegisteredTeacher');

Route::post('/users/{user}/photo', 'UserController@storePhoto')
	->name('user.storePhoto');

Route::post('/users/{user}/identification', 'UserController@storeIdentification')
	->name('user.storeIdentification');

Route::post('/users/{user}/qualifications', 'UserController@storeQualifications')
	->name('user.storeQualifications');

Route::post('/users/{user}/gift', 'UserController@gift')
	->name('user.gift');

Route::put('/users/{user}/photo', 'UserController@replacePhoto')
	->name('user.replacePhoto');

Route::delete('/users/{user}/photo', 'UserController@deletePhoto')
	->name('user.deletePhoto');

Route::delete('/users/{user}/identification', 'UserController@deleteIdentification')
	->name('user.deleteIdentification');

Route::delete('/users/{user}/qualifications', 'UserController@deleteQualifications')
	->name('user.deleteQualifications');

Route::delete('/users/{user}', 'UserController@destroy')
	->name('user.destroy');


// LESSONS
Route::get('/lessons', 'LessonController@index')
	->name('lesson.index');

Route::get('/lessons/create', 'LessonController@create')
	->name('lesson.create');

Route::get('/lessons/{lesson}', 'LessonController@show')
	->name('lesson.show');

Route::get('/lessons/{lesson}/edit', 'LessonController@edit')
	->name('lesson.edit');

Route::patch('/lessons/{lesson}', 'LessonController@update')
	->name('lesson.update');

Route::post('/lessons', 'LessonController@store')
	->name('lesson.store');

Route::post('/lessons/{lesson}/photo', 'LessonController@storePhoto')
	->name('lesson.storePhoto');

Route::post('/lessons/{lesson}/subscriptions/enable', 'LessonController@enableSubscriptions')
	->name('lesson.enableSubscriptions');

Route::post('/lessons/{lesson}/subscriptions/disable', 'LessonController@disableSubscriptions')
	->name('lesson.disableSubscriptions');

Route::put('/lessons/{lesson}/photo', 'LessonController@replacePhoto')
	->name('lesson.replacePhoto');

Route::delete('/lessons/{lesson}', 'LessonController@destroy')
	->name('lesson.destroy')
	->middleware($throttle_60);

Route::delete('/lessons/{lesson}/photo', 'LessonController@deletePhoto')
	->name('lesson.deletePhoto');


// CLASSROOMS
Route::get('/lessons/{lesson}/classrooms/create', 'ClassroomController@create')
	->name('classroom.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}', 'ClassroomController@show')
	->name('classroom.show');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/edit', 'ClassroomController@edit')
	->name('classroom.edit');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/video/upload', 'ClassroomController@uploadVideo')
	->name('classroom.uploadVideo')
	->middleware($throttle_15);

Route::get('/classrooms/{classroom}/video/uploaded', 'ClassroomController@uploadVideoComplete')
	->name('classroom.uploadVideoComplete');

Route::patch('/classrooms/{classroom}', 'ClassroomController@update')
	->name('classroom.update');

Route::post('/lessons/{lesson}/classrooms', 'ClassroomController@store')
	->name('classroom.store');

Route::post('/classrooms/{classroom}/attachment', 'ClassroomController@storeAttachment')
	->name('classroom.storeAttachment');

Route::post('/classrooms/{classroom}/publish', 'ClassroomController@publish')
	->name('classroom.publish');

Route::post('/classrooms/{classroom}/unpublish', 'ClassroomController@unpublish')
	->name('classroom.unpublish');

Route::delete('/classrooms/{classroom}', 'ClassroomController@destroy')
	->name('classroom.destroy')
	->middleware($throttle_15);

Route::delete('/classrooms/{classroom}/video', 'ClassroomController@deleteVideo')
	->name('classroom.deleteVideo')
	->middleware($throttle_15);

Route::delete('/classrooms/{classroom}/attachment', 'ClassroomController@deleteAttachment')
	->name('classroom.deleteAttachment');


// PROGRESS
Route::post('/classrooms/{classroom}/progresses', 'ProgressController@store')
	->name('progress.store');


// ASSIGNMENTS
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments', 'AssignmentController@index')
	->name('assignment.index');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments/create', 'AssignmentController@create')
	->name('assignment.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments/{assignment_number}/edit', 'AssignmentController@edit')
	->name('assignment.edit');

Route::patch('/assignment/{assignment}', 'AssignmentController@update')
	->name('assignment.update');

Route::post('/classrooms/{classroom}/assignments', 'AssignmentController@store')
	->name('assignment.store');

Route::delete('/assignment/{assignment}', 'AssignmentController@destroy')
	->name('assignment.destroy');


// QUIZZES
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes', 'QuizController@index')
	->name('quiz.index');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/create', 'QuizController@create')
	->name('quiz.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}', 'QuizController@show')
	->name('quiz.show');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/edit', 'QuizController@edit')
	->name('quiz.edit');

Route::patch('/quizzes/{quiz}', 'QuizController@update')
	->name('quiz.update');

Route::post('/classrooms/{classroom}/quizzes', 'QuizController@store')
	->name('quiz.store');

Route::delete('/quizzes/{quiz}', 'QuizController@destroy')
	->name('quiz.destroy');


// QUESTIONS
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/questions/create', 'QuestionController@create')
	->name('question.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/questions/{question_number}/edit', 'QuestionController@edit')
	->name('question.edit');

Route::patch('/questions/{question}', 'QuestionController@update')
	->name('question.update');

Route::post('/quizzes/{quiz}/questions', 'QuestionController@store')
	->name('question.store');

Route::post('/questions/{question}/photo', 'QuestionController@storePhoto')
	->name('question.storePhoto');

Route::put('/questions/{question}/photo', 'QuestionController@replacePhoto')
	->name('question.replacePhoto');

Route::delete('/questions/{question}', 'QuestionController@destroy')
	->name('question.destroy');

Route::delete('/questions/{question}/photo', 'QuestionController@deletePhoto')

app/Lesson.php
<?php

namespace App;

use App\Defaults\Subject;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Laravel\Scout\Searchable;

class Lesson extends Model {

	use Searchable;

	const MAX_DESCRIPTION_LENGTH = 280;

	public $asYouType = true;

	// The attributes that are mass assignable.
	protected $fillable = [

	    'photo', 'subject', 'level', 'price', 'description', 'last_publish_date', 'subscriptions_disabled', 'marked_for_deletion'
	    
	];

	// The attributes that should be shown for arrays.
	protected $visible = [

	    'id', 'photo', 'subject', 'level', 'price', 'description', 'last_publish_date', 'subscriptions_disabled', 'marked_for_deletion'

	];

	public function __construct(array $attributes = array(), $photo = null) {

        // Eloquent
		parent::__construct($attributes);

		if (isset($photo)) {

			$this->photo = self::savePhoto($photo);

		}

	}

	public function user() {

	    return $this->belongsTo(User::class);

	}

	public function classrooms() {

	    return $this->hasMany(Classroom::class);

	}

	public function reviews() {

		return $this->hasMany(Review::class);

	}

	public function subscriptions() {

	    return $this->hasMany(Subscription::class);

	}

	public function getActiveSubscriptionsCountAttribute() {

		$count = 0;

		$this->subscriptions->each(function($subscription) use (&$count) {
			if ($subscription->isActive()) {
				$count++;
			}
		});

		return $count;
		
	}

	public function getPrettyIDAttribute() {

		$id = str_replace(" ", "-", $this->id);
		$level = str_replace(" ", "-", $this->level);
		$subject = str_replace(" ", "-", $this->subject); 
		$teacher_name = str_replace(" ", "-", $this->user->name);

		return "$id-$level-$subject-$teacher_name";

	}

	public function getUnwatchedClassroomsAttribute() {
		
		$count = 0;

		$this->classrooms->each(function($classroom) use (&$count){
            
			if (!$classroom->progress_completed && $classroom->isPublished()) {
				$count++;
			}

        });

		return $count;

	}

	public function getRatingAttribute() {

		$avg = $this->reviews->avg('rating');

		return $this->reviews->isNotEmpty() ?  round($avg) : 0;

	}

	public function getPhotoUrlAttribute() {

		if (isset($this->photo)) {

			return Storage::disk('spaces')->url($this->photo);

		}
		return (resolve(Subject::class))->getPhotoUrl($this->subject);

	}

	/**
	 * Get the indexable data array for the model.
	 *
	 * @return array
	 */
	public function toSearchableArray() {

	    $array = $this->toArray();

	    return [
	    	'id' => $array['id'],
	    	'subject' => $array['subject'],
	    	'level' => $array['level'],
	    	'description' => $array['description'],
	    ];

	}

	public function getClassroomByNumber($classroom_number) {

		if ($classroom = $this->classrooms->get($classroom_number - 1)) {
			return $classroom;
		}
		
		abort(404, 'Classroom not found.');

	}

	public function getReviewByNumber($review_number) {

		if ($review = $this->reviews->get($review_number - 1)) {
			return $review;
		}

		abort(404, 'Review not found.');
	}

	public function addClassroom(Classroom $classroom) {

		return $this->classrooms()->save($classroom);

	}

	public function deletePhoto() {

		if (isset($this->photo)) {

			Storage::disk('spaces')->delete($this->photo);

			$this->update([
			    'photo' => null
			]);

		}

		return $this;
		
	}

	public function uploadPhoto($photo) {
		
		$photo_uri =  self::savePhoto($photo);

		$this->update([
		    'photo' => $photo_uri
		]);

	}

	public function updateLatestPublishDate() {
		
		$last_publish_date = $this->created_at;
		$classrooms = $this->classrooms;

		$classrooms->each(function($classroom) use (&$last_publish_date) {
			if ($classroom->isPublished()) {
				if (Carbon::parse($classroom->publish_date)->gt(Carbon::parse($last_publish_date))) {
					$last_publish_date = $classroom->publish_date;
				}
			}
		});

		$this->update([
			'last_publish_date' => Carbon::parse($last_publish_date)
		]);

		return $last_publish_date;

	}

	public function getNextClassroom($classroom_number) {

		$classrooms = $this->classrooms;
		$next_classroom = null;

		$classrooms->each(function($classroom, $key) use(&$classroom_number, &$next_classroom) {
			$number = $key + 1;
			if (($number > $classroom_number) && ($classroom->isPublished())) {
				$next_classroom = $classroom;
				return false;
			}
		});

		return $next_classroom;
		
	}

	public function isSubscriptionsDisabled() {
		
		return $this->subscriptions_disabled === 1;

	}

	public function enableSubscriptions() {
		
		$this->update([
			'subscriptions_disabled' => 0
		]);

		return $this;

	}

	public function disableSubscriptions() {
		
		$this->update([
			'subscriptions_disabled' => 1
		]);

		return $this;

	}

	public static function getMaxDescriptionLength() {

		return self::MAX_DESCRIPTION_LENGTH;

	}

	private static function savePhoto($photo) {

		$path = 'uploads/lessons/photos/'.$photo->hashName();
		$img = Image::make($photo)->fit(1920, 1080)->encode();
		
		return Storage::disk('spaces')->put($path, (string) $img, 'public') ? $path : null;

	}
	
}

resources/views/lesson/create.blade.php
@extends ('layouts.form')

@section ('title', 'Creating Lesson')

@section ('subtitle', 'Students will be able to subscribe to your lesson.')

@section ('form')

    @component ('components.form.master', ['method' => 'POST', 'form_action' => 'Create Lesson', 'url' => route('lesson.store'), 'enctype' => 'multipart/form-data', 'csrf_token' => csrf_token()])

        @component ('components.form.select', ['name'=> 'subject', 'errors' => $errors, 'list' => $subject_list])
            Subject
        @endcomponent

        @component ('components.form.select', ['name'=> 'level', 'errors' => $errors, 'list' => $level_list])
            Level
        @endcomponent

        @component ('components.form.textarea', ['name'=> 'description', 'errors' => $errors, 'max_characters' => \App\Lesson::getMaxDescriptionLength(), 'value'=> old('description')])
            Description
        @endcomponent

        @component ('components.form.file', ['name'=> 'photo', 'errors' => $errors, 'not_required' => true])
            Lesson Photo (optional)
        @endcomponent

    @endcomponent

@endsection

resources/views/lesson/delete-photo.blade.php
@component ('components.form.master', ['method' => 'DELETE', 'form_action' => 'Delete Photo', 'btn_class' => 'btn-danger','url' => route('lesson.deletePhoto', ['lesson' => $lesson->id]), 'csrf_token' => csrf_token()])
@endcomponent

resources/views/lesson/destroy.blade.php
@component ('components.form.master', ['method' => 'DELETE', 'form_action' => 'Delete Lesson', 'btn_class' => 'btn-danger', 'url' => route('lesson.destroy', ['lesson' => $lesson->id]), 'csrf_token' => csrf_token()])
@endcomponent

resources/views/lesson/edit.blade.php
@extends ('layouts.form')

@section ('title', 'Updating Lesson')

@section ('subtitle')
    <a href="{{ route('lesson.show', ['lesson' => $lesson->pretty_id]) }}">{{$lesson->level}} {{$lesson->subject}}</a>
@endsection

@section ('form')

    @if (auth()->user()->isAdmin())
        <h3 class="text-center">Lesson Status (Admin Only)</h3>
        <p class="lead text-center">Subscriptions for this Lesson are currently {!! ($lesson->isSubscriptionsDisabled()) ? '<span class="text-danger">Disabled</span>' : '<span class="text-secondary">Enabled</span>' !!}.</p>
        <div class="row justify-content-center mb-2">
            @can ('enableSubscriptions', [\App\Lesson::class, $lesson])
                <form action="{{ route('lesson.enableSubscriptions', ['lesson' => $lesson->id]) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="submit" value="Enable Lesson" class="btn btn-secondary text-white">
                </form>
            @endcan
            @can ('disableSubscriptions', [\App\Lesson::class, $lesson])
                <form action="{{ route('lesson.disableSubscriptions', ['lesson' => $lesson->id]) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="submit" value="Disable Lesson" class="btn btn-secondary text-white">
                </form>
            @endcan
        </div>
        <hr>
    @endif

    @component ('components.form.master', ['method' => 'PATCH', 'form_action' => 'Update Lesson','url' => route('lesson.update', ['lesson' => $lesson->id]), 'csrf_token' => csrf_token()])

        @component ('components.form.select', ['name'=> 'subject', 'errors' => $errors, 'value' => $lesson->subject, 'list' => $subject_list])
            Subject
        @endcomponent

        @component ('components.form.select', ['name'=> 'level', 'errors' => $errors, 'value' => $lesson->level, 'list' => $level_list])
            Level
        @endcomponent

        @component ('components.form.textarea', ['name'=> 'description', 'errors' => $errors, 'max_characters' => \App\Lesson::getMaxDescriptionLength(), 'value'=> $lesson->description])
            Description
        @endcomponent

    @endcomponent

    <hr>

    <div class="row text-muted justify-content-center">
        <p class="text-center">Lesson Photo</p>
    </div>

    <div class="row mb-3">
        <div class="col-sm-6">
            <img class="card-img-top rounded-0" src="{{ $lesson->photo_url }}" alt="{{ $lesson->level }} {{ $lesson->subject }} Lesson Photo">
        </div>
        <div class="col-sm-6 text-center pt-2">
            @can ('uploadPhoto', [\App\Lesson::class, $lesson])
                @include ('lesson.upload-photo')
            @endcan

            @can ('deletePhoto', [\App\Lesson::class, $lesson])
                @include ('lesson.replace-photo')
            @endcan
        </div>
    </div>

   
    @can ('deletePhoto', [\App\Lesson::class, $lesson])
        <div class="row justify-content-center">
            @include ('lesson.delete-photo')
        </div>
    @endcan
    
    @can ('delete', [\App\Lesson::class, $lesson])
        <hr class="mt-0">
        <h3 class="text-center">Delete Lesson (Admin Only)</h3>
        <div class="row mb-3 justify-content-center">
            @include ('lesson.destroy')
        </div>
    @endcan

@endsection

resources/views/lesson/my-lessons.blade.php
@extends ('layouts.app')

@section ('title', 'My Lessons')

@section ('content')

  @component ('components.lesson.list')

    @slot ('title', 'My Lessons')

    @slot('subtitle')
      <a href="{{ route('lesson.create') }}">Create Lesson</a>
    @endslot

    <div class="container-fluid">

       <div class="row justify-content-center">
           <div class="col-lg-9">
              <div class="row">
                <div class="container-fluid text-center mt-3">
                  @include ('flash::message')
                </div>
              </div>
              <div class="row mb-3">

                @if ($lessons->count() > 0)
                  @foreach ($lessons as $lesson)

                      <div class="col-12 col-md-6">

                          @component ('components.lesson.card', ['lesson' => $lesson, 'lesson_url' => route('lesson.show', ['lesson' => $lesson->pretty_id])])
                          @endcomponent

                      </div>

                  @endforeach
                @else
                  <div class="row justify-content-center">
                    <div class="col-10 col-md-8 p-2 mb-3">
                      <img src="https://learnermaxima.nyc3.digitaloceanspaces.com/assets/pages/lessons/no-lessons.png" alt="No Subscriptions" class="img-fluid">
                    </div>
                  </div>
                @endif
              </div>
              @can ('create', \App\Lesson::class)
                <div class="text-center">
                  <a href="{{ route('lesson.create') }}" class="btn btn-secondary text-white">Create Lesson</a>
                </div>
              @endcan
           </div>
       </div>
       
    </div>

  @endcomponent
  
@endsection

resources/views/lesson/replace-photo.blade.php
@component ('components.form.master',['method' => 'PUT', 'form_action' => 'Replace Photo','url' => route('lesson.replacePhoto', ['lesson' => $lesson->id]), 'enctype' => 'multipart/form-data', 'csrf_token' => csrf_token()])

    @component ('components.form.file', ['name'=> 'photo'])
        Photo
    @endcomponent

@endcomponent

resources/views/lesson/show.blade.php
@extends ('layouts.app')

@section ('title')
	{{ $lesson->level }} {{ $lesson->subject}}, taught by {{$lesson->user->name }}
@endsection

@section ('meta-description', "Learn $lesson->level $lesson->subject, taught by ".$lesson->user->name." on ".config('app.name')." - ".config('app.description'))

@section ('content')
	@component('components.banner.large')
		<div class="container">
			<div class="row pt-4">
				<div class="col-12 col-lg-6">
					<a href="{{ route('lesson.index') }}?sort=newest-to-oldest&level={{ urlencode($lesson->level) }}&subject=all-subjects" class="pl-3 pr-3 font-weight-light bg-primary text-white">
						{{ $lesson->level }}
					</a>
					<h2>
						{{ $lesson->subject }}
						@can ('update', [\App\Lesson::class, $lesson])
							<small><a href={{ route('lesson.edit', ['lesson' => $lesson->pretty_id]) }} class="ion-gear-b text-secondary"></a></small>
						@endcan
					</h2>
					<p class="text-uppercase font-weight-light">
						<a href="{{ route('user.show', ['user' => $lesson->user->pretty_id]) }}">
						    @if ($lesson->user->isRegisteredTeacher())
						        <i class="ion-ribbon-b" title="Teacher"></i> Teacher:
						    @elseif ($lesson->user->isTeacher())
						        <i class="ion-ribbon-a" title="Tutor"></i> Tutor:
						    @endif
						    {{ $lesson->user->name }}
						</a>
						@if (isset($lesson->user->public_contact_email))
							<br>
							<small class="text-uppercase font-weight-light">EMAIL: <a href="mailto:{{ $lesson->user->public_contact_email }}">{{ $lesson->user->public_contact_email }}</a></small>
						@endif
						<br>
						<small class="text-uppercase font-weight-light text-secondary">
							Last Updated {{ Carbon\Carbon::parse($lesson->last_publish_date)->diffForHumans() }}
						</small>
						@if( isset($subscription) )
							<br>
							@if ($subscription->days_remaining === 0)
								<div class="badge badge-danger text-uppercase text-white">
									Expires Today
								</div>
							@else
								<div class="badge badge-secondary text-uppercase text-white">
									{{ $subscription->days_remaining }} Days Remaining
								</div>
							@endif
						@endif
						@can ('update', [\App\Lesson::class, $lesson])
							<br>
							<div class="badge badge-secondary text-uppercase text-white">
								Students: {{ $lesson->active_subscriptions_count }}
							</div>
							@if (!Auth::guest() && auth()->user()->isAdmin())
								@if ($lesson->isSubscriptionsDisabled())
								    <div class="badge badge-danger text-uppercase text-white">Lesson Disabled</div>
								@else
								    <div class="badge badge-secondary text-uppercase text-white">Lesson Enabled</div>
								@endif
							@endif
						@endcan
					</p>
					<p class="text-gray-300">
						{{ $lesson->description }}
					</p>
				</div>
				<div class="col-12 col-lg-6 pt-4 pb-4">
					<img class="card-img-top rounded-0" src="{{ $lesson->photo_url }}" alt="{{ $lesson->level }} {{ $lesson->subject }} Lesson Photo">
				</div>
			</div>

			<div class="row pb-4">
				<div class="col d-flex">
					<div class="align-self-center m-auto text-center">

						@can ('create', [\App\Subscription::class, $lesson])
							<a href="{{ route('subscription.create', ['lesson' => $lesson->pretty_id]) }}" class="btn btn-secondary text-white">Subscribe</a>							
						@endcan
						
						@if( isset($subscription))
							@can ('renew', [\App\Subscription::class, $subscription])
								<p class="lead text-center">Your subscription is up for renewal. Please do so if you wish to remain subscribed.</p>
								<a href="{{ route('subscription.createRenew', ['lesson' => $lesson->pretty_id]) }}" class="btn btn-secondary text-white">Renew</a>							
							@endcan
						@endif

						@if( isset($subscription) && $subscription->days_remaining === 0)
							<br>
							<p class="lead text-center">Your subscription expires today. You'll have the option to re-subscribe after it expires. Renewals can only be done 1-7 days before expiry.</p>
						@endif

						@can ('create', [\App\Classroom::class, $lesson])
							<a href="{{ route('classroom.create', ['lesson' => $lesson->pretty_id])}}" class="btn btn-secondary text-white">Create Classroom</a>
						@endcan

						@if (Auth::guest())
							<p class="lead">You must be logged in and subscribed to this Lesson to continue.</p>
							<a href="{{ route('login')}}?redirect_to={{ request()->path() }}" class="btn btn-secondary text-white">Login / Signup</a>
						@endif
						
						<hr>

						@component ('components.lesson.rating', ['rating' => $lesson->rating])
						@endcomponent

					</div>
				</div>
			</div>
		</div>
	@endcomponent
	<div class="container">
		@include ('classroom.index')
		@include ('review.index')	
	</div>
@endsection

@section ('scripts')
	<script>
	  fbq('track', 'ViewContent');
	</script>
@endsection

resources/views/lesson/upload-photo.blade.php
@component ('components.form.master',['method' => 'POST', 'form_action' => 'Upload Photo','url' => route('lesson.storePhoto', ['lesson' => $lesson->id]), 'enctype' => 'multipart/form-data', 'csrf_token' => csrf_token()])

    @component ('components.form.file', ['name'=> 'photo'])
        Photo
    @endcomponent

@endcomponent