routes/web.php
	->name('user.showUpgradeToRegisteredTeacher');

Route::get('/users/{user}/become-a-tutor-or-teacher', 'UserController@showBecomeATeacher')
	->name('user.showBecomeATeacher');

Route::get('/users/{user}/profile/edit', 'UserController@editProfile')
	->name('user.editProfile');

Route::patch('/users/{user}', 'UserController@update')
	->name('user.update');

Route::patch('/users/{user}/profile', 'UserController@updateProfile')
	->name('user.updateProfile');

Route::patch('/users/{user}/payout', 'UserController@updatePayoutDetails')
	->name('user.updatePayoutDetails');

Route::post('/users/{user}/payoff', 'UserController@payOff')
	->name('user.payOff');

Route::post('/users/{user}/upgrade', 'UserController@upgrade')
	->name('user.upgrade');

Route::post('/users/{user}/upgrade/cancel', 'UserController@cancelUpgrade')
	->name('user.cancelUpgrade');

Route::post('/users/{user}/downgrade', 'UserController@downgrade')
	->name('user.downgrade');

Route::post('/users/{user}/become-a-tutor-teacher', 'UserController@becomeATeacher')
	->name('user.becomeATeacher');

Route::post('/users/{user}/upgrade-to-teacher', 'UserController@upgradeToRegisteredTeacher')
	->name('user.upgradeToRegisteredTeacher');

Route::post('/users/{user}/photo', 'UserController@storePhoto')
	->name('user.storePhoto');

Route::post('/users/{user}/identification', 'UserController@storeIdentification')
	->name('user.storeIdentification');

Route::post('/users/{user}/qualifications', 'UserController@storeQualifications')
	->name('user.storeQualifications');

Route::post('/users/{user}/gift', 'UserController@gift')
	->name('user.gift');

Route::put('/users/{user}/photo', 'UserController@replacePhoto')
	->name('user.replacePhoto');

Route::delete('/users/{user}/photo', 'UserController@deletePhoto')
	->name('user.deletePhoto');

Route::delete('/users/{user}/identification', 'UserController@deleteIdentification')
	->name('user.deleteIdentification');

Route::delete('/users/{user}/qualifications', 'UserController@deleteQualifications')
	->name('user.deleteQualifications');

Route::delete('/users/{user}', 'UserController@destroy')
	->name('user.destroy');


// LESSONS
Route::get('/lessons', 'LessonController@index')
	->name('lesson.index');

Route::get('/lessons/create', 'LessonController@create')
	->name('lesson.create');

Route::get('/lessons/{lesson}', 'LessonController@show')
	->name('lesson.show');

Route::get('/lessons/{lesson}/edit', 'LessonController@edit')
	->name('lesson.edit');

Route::patch('/lessons/{lesson}', 'LessonController@update')
	->name('lesson.update');

Route::post('/lessons', 'LessonController@store')
	->name('lesson.store');

Route::post('/lessons/{lesson}/photo', 'LessonController@storePhoto')
	->name('lesson.storePhoto');

Route::post('/lessons/{lesson}/subscriptions/enable', 'LessonController@enableSubscriptions')
	->name('lesson.enableSubscriptions');

Route::post('/lessons/{lesson}/subscriptions/disable', 'LessonController@disableSubscriptions')
	->name('lesson.disableSubscriptions');

Route::put('/lessons/{lesson}/photo', 'LessonController@replacePhoto')
	->name('lesson.replacePhoto');

Route::delete('/lessons/{lesson}', 'LessonController@destroy')
	->name('lesson.destroy')
	->middleware($throttle_60);

Route::delete('/lessons/{lesson}/photo', 'LessonController@deletePhoto')
	->name('lesson.deletePhoto');


// CLASSROOMS
Route::get('/lessons/{lesson}/classrooms/create', 'ClassroomController@create')
	->name('classroom.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}', 'ClassroomController@show')
	->name('classroom.show');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/edit', 'ClassroomController@edit')
	->name('classroom.edit');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/video/upload', 'ClassroomController@uploadVideo')
	->name('classroom.uploadVideo')
	->middleware($throttle_15);

Route::get('/classrooms/{classroom}/video/uploaded', 'ClassroomController@uploadVideoComplete')
	->name('classroom.uploadVideoComplete');

Route::patch('/classrooms/{classroom}', 'ClassroomController@update')
	->name('classroom.update');

Route::post('/lessons/{lesson}/classrooms', 'ClassroomController@store')
	->name('classroom.store');

Route::post('/classrooms/{classroom}/attachment', 'ClassroomController@storeAttachment')
	->name('classroom.storeAttachment');

Route::post('/classrooms/{classroom}/publish', 'ClassroomController@publish')
	->name('classroom.publish');

Route::post('/classrooms/{classroom}/unpublish', 'ClassroomController@unpublish')
	->name('classroom.unpublish');

Route::delete('/classrooms/{classroom}', 'ClassroomController@destroy')
	->name('classroom.destroy')
	->middleware($throttle_15);

Route::delete('/classrooms/{classroom}/video', 'ClassroomController@deleteVideo')
	->name('classroom.deleteVideo')
	->middleware($throttle_15);

Route::delete('/classrooms/{classroom}/attachment', 'ClassroomController@deleteAttachment')
	->name('classroom.deleteAttachment');


// PROGRESS
Route::post('/classrooms/{classroom}/progresses', 'ProgressController@store')
	->name('progress.store');


// ASSIGNMENTS
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments', 'AssignmentController@index')
	->name('assignment.index');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments/create', 'AssignmentController@create')
	->name('assignment.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments/{assignment_number}/edit', 'AssignmentController@edit')
	->name('assignment.edit');

Route::patch('/assignment/{assignment}', 'AssignmentController@update')
	->name('assignment.update');

Route::post('/classrooms/{classroom}/assignments', 'AssignmentController@store')
	->name('assignment.store');

Route::delete('/assignment/{assignment}', 'AssignmentController@destroy')
	->name('assignment.destroy');


// QUIZZES
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes', 'QuizController@index')
	->name('quiz.index');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/create', 'QuizController@create')
	->name('quiz.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}', 'QuizController@show')
	->name('quiz.show');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/edit', 'QuizController@edit')
	->name('quiz.edit');

Route::patch('/quizzes/{quiz}', 'QuizController@update')
	->name('quiz.update');

Route::post('/classrooms/{classroom}/quizzes', 'QuizController@store')
	->name('quiz.store');

Route::delete('/quizzes/{quiz}', 'QuizController@destroy')
	->name('quiz.destroy');


// QUESTIONS
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/questions/create', 'QuestionController@create')
	->name('question.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/questions/{question_number}/edit', 'QuestionController@edit')
	->name('question.edit');

Route::patch('/questions/{question}', 'QuestionController@update')
	->name('question.update');

Route::post('/quizzes/{quiz}/questions', 'QuestionController@store')
	->name('question.store');

Route::post('/questions/{question}/photo', 'QuestionController@storePhoto')
	->name('question.storePhoto');

Route::put('/questions/{question}/photo', 'QuestionController@replacePhoto')
	->name('question.replacePhoto');

Route::delete('/questions/{question}', 'QuestionController@destroy')
	->name('question.destroy');

Route::delete('/questions/{question}/photo', 'QuestionController@deletePhoto')
	->name('question.deletePhoto');


// ANSWERS
Route::post('/quizzes/{quiz}/answers', 'AnswerController@store')
	->name('answer.store');


// DISCUSSIONS
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/discussions/create', 'DiscussionController@create')
	->name('discussion.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/discussions/{discussion_number}/edit', 'DiscussionController@edit')
	->name('discussion.edit');

Route::patch('/discussions/{discussion}', 'DiscussionController@update')
	->name('discussion.update');

Route::post('/classrooms/{classroom}/discussions', 'DiscussionController@store')
	->name('discussion.store');

Route::delete('/discussions/{discussion}', 'DiscussionController@destroy')
	->name('discussion.destroy');


// REVIEWS

Route::get('/lessons/{lesson}/reviews/create', 'ReviewController@create')
	->name('review.create');

Route::get('/lessons/{lesson}/reviews/{review_number}/edit', 'ReviewController@edit')
	->name('review.edit');

Route::patch('/reviews/{review}', 'ReviewController@update')
	->name('review.update');

Route::post('/lessons/{lesson}/reviews', 'ReviewController@store')
	->name('review.store');

Route::delete('/reviews/{review}', 'ReviewController@destroy')
	->name('review.destroy');


// SUBSCRIPTIONS, ORDERS AND PAYMENTS
Route::get('/lessons/{lesson}/subscribe', 'SubscriptionController@create')
	->name('subscription.create');

Route::get('/lessons/{lesson}/renew', 'SubscriptionController@createRenew')
	->name('subscription.createRenew');

Route::get('/lessons/{lesson}/subscribe-for-free', 'SubscriptionController@createFree')
	->name('subscription.createFree');

Route::get('/lessons/{lesson}/subscribe/pay', 'SubscriptionController@createOrder')
	->name('subscription.createOrder')
	->middleware($throttle_15);

Route::get('/lessons/{lesson}/renew/pay', 'SubscriptionController@createRenewOrder')
	->name('subscription.createRenewOrder')
	->middleware($throttle_15);

Route::get('/lessons/{lesson}/subscriptions', 'SubscriptionController@index')
	->name('subscription.index');

Route::get('/subscriptions/order/{subscription}', 'SubscriptionController@show')
	->name('subscription.show');

Route::get('/subscriptions/process/wipay', 'SubscriptionController@processWipayOrder')
	->name('subscription.processWipayOrder');

app/Classroom.php
<?php

namespace App;

use App\Videos\Vimeo;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;

class Classroom extends Model {

    const MAX_OBJECTIVE_LENGTH = 280;

	protected $vimeo;

	// The attributes that are mass assignable.
	protected $fillable = [

	    'title', 'objective', 'video', 'attachment', 'upload_link_secure', 'publish_date'
	    
	];

	// The attributes that should be shown for arrays.
	protected $visible = [

	    'id', 'title', 'objective', 'video', 'attachment', 'upload_link_secure', 'publish_date'

	];

	public function __construct(array $attributes = array(), $attachment = null) {

        // Eloquent
		parent::__construct($attributes);

	    $this->vimeo = resolve(Vimeo::class);

        if (isset($attachment)) {

            $this->attachment = self::saveAttachment($attachment);

        }

	}

    public function lesson() {

        return $this->belongsTo(Lesson::class);
        
    }

    public function progresses() {

        return $this->hasMany(Progress::class);

    }

    public function assignments() {

        return $this->hasMany(Assignment::class);

    }

    public function quizzes() {

        return $this->hasMany(Quiz::class);

    }

    public function discussions() {

        return $this->hasMany(Discussion::class);

    }

    public function getNumberAttribute() {

        $lesson = $this->lesson;

        $results = $lesson->classrooms->pluck('id')->search($this->id) + 1;

        return $results ? $results : null;
        
    }

    public function getAttachmentDownloadPathAttribute() {

        return env('SPACES_URL').'/'.$this->attachment;

    }

    public function getProgressCompletedAttribute() {

        if (auth()->user() !== null) {

            $progress = Progress::where(['user_id' => auth()->user()->id, 'classroom_id' => $this->id])->first();

            return isset($progress);

        }

        return false;

    }

    public function getRootDiscussionsAttribute() {

        return $this->discussions->filter(function($discussion, $index) {
            return !isset($discussion->replyto);
        });
        
    }

    public function isPublished() {

        return isset($this->publish_date);
        
    }

    public function publish() {
        
        $this->update(['publish_date' => Carbon::now()]);
        $this->lesson->updateLatestPublishDate();
        return $this;

    }

    public function unpublish() {
        
        $this->update(['publish_date' => null]);
        $this->lesson->updateLatestPublishDate();
        return $this;

    }

    public function getAssignmentByNumber($assignment_number) {

        if ($assignment = $this->assignments->get($assignment_number - 1)) {
            return $assignment;
        }
        
        abort(404, 'Assignment not found.');

    }

    public function getQuizByNumber($quiz_number) {

        if ($quiz = $this->quizzes->get($quiz_number - 1)) {

            return $quiz;
            
        }
        
        abort(404, 'Quiz not found.');

    }

    public function getDiscussionByNumber($discussion_number) {

        if ($discussion = $this->discussions->get($discussion_number - 1)) {
            return $discussion;
        }
        
        abort(404, 'Discussion not found.');

    }

    public function getVideoUploadLinkSecure($return_route_string) {
    	
    	if (!isset($this->upload_link_secure)) {

    	    $upload_info = $this->vimeo->getVideoUploadInfo(route($return_route_string, ['classroom' => $this->id]));
    	    $this->update($upload_info);

    	}

    	return $this->upload_link_secure;

    }

    public function addAssignment(Assignment $assignment) {

        return $this->assignments()->save($assignment);

    }

    public function addQuiz(Quiz $quiz) {

        return $this->quizzes()->save($quiz);

    }

    public function updateVideoData($video_data) {

    	// Get Video ID
    	$video_id = $this->vimeo->getVideoID($video_data);

    	// Associate with Classroom
    	$this->update([
    	        'video' => $video_id
    	    ]);

    	// Get relevant variables
    	$lesson = $this->lesson;
    	$user = $lesson->user;

    	// Format Video Title and Description
    	$video_title = "Classroom $this->id";
    	$video_description = "Classroom $this->id taught by User $user->id in Lesson $lesson->id";

    	// Set Video Title and Description
    	$this->vimeo->setVideoMetaData($video_id, $video_title, $video_description);
    	
    }

    public function getVideoEmbed() {
        return $this->vimeo->getEmbed($this->video);
    }

    public function deleteVideo() {

    	if (isset($this->video)) {

    		$this->vimeo->deleteVideo($this->video);

    		$this->update([
    		    'video' => null,
    		    'upload_link_secure' => null
    		]);

    	}

    	return $this;
    	
    }

    public function deleteAttachment() {

        if (isset($this->attachment)) {

            Storage::disk('spaces')->delete($this->attachment);

            $this->update([
                'attachment' => null
            ]);

        }

        return $this;
        
    }

    public function uploadAttachment($file) {
        
        $file_uri =  self::saveAttachment($file);

        $this->update([
            'attachment' => $file_uri
        ]);

    }

    public static function getMaxObjectiveLength() {

        return self::MAX_OBJECTIVE_LENGTH;

    }

    private static function saveAttachment($attachment) {

        $location = 'uploads/classrooms/attachments';
        $path = $location.'/'.$attachment->hashName();

        return Storage::disk('spaces')->putFile($location, $attachment, 'public') ? $path : null;

    }

}

resources/views/classroom/create.blade.php
@extends ('layouts.form')

@section ('title', 'Creating Classroom')

@section ('subtitle')
	<a href="{{ route('lesson.show', ['lesson' => $lesson->pretty_id]) }}">{{$lesson->level}} {{$lesson->subject}}</a>
@endsection

@section ('form')

    @component ('components.form.master', ['method' => 'POST', 'form_action' => 'Create Classroom','url' => route('classroom.store', ['lesson' => $lesson->id]), 'enctype' => 'multipart/form-data', 'csrf_token' => csrf_token()])

        @component ('components.form.input', ['name'=> 'title', 'type'=> 'text', 'errors' => $errors, 'value'=> old('title')])
            Title
        @endcomponent

        @component ('components.form.textarea', ['name'=> 'objective', 'errors' => $errors, 'max_characters' => \App\Classroom::getMaxObjectiveLength(), 'value'=> old('objective')])
            Objective
        @endcomponent

        @component ('components.form.file', ['name'=> 'attachment', 'errors' => $errors, 'not_required' => true])
            Notes (optional) - Word Document, PDF, Powerpoint, Zip etc.
        @endcomponent

    @endcomponent

@endsection

resources/views/classroom/delete-attachment.blade.php
@component ('components.form.master', ['method' => 'DELETE', 'form_action' => 'Delete Notes', 'btn_class' => 'btn-danger','url' => route('classroom.deleteAttachment', ['classroom' => $classroom->id]), 'csrf_token' => csrf_token()])
@endcomponent

resources/views/classroom/delete-video.blade.php
@component ('components.form.master', ['method' => 'DELETE', 'form_action' => 'Delete Video', 'btn_class' => 'btn-danger','url' => route('classroom.deleteVideo', ['classroom' => $classroom->id]), 'csrf_token' => csrf_token()])
@endcomponent

resources/views/classroom/destroy.blade.php
@component ('components.form.master', ['method' => 'DELETE', 'form_action' => 'Delete Classroom', 'btn_class' => 'btn-danger float-right','url' => route('classroom.destroy', ['classroom' => $classroom->id]), 'csrf_token' => csrf_token()])
@endcomponent

resources/views/classroom/edit.blade.php
@extends ('layouts.form')

@section ('title', 'Updating your Classroom')

@section ('subtitle')
    <a href="{{ route('classroom.show', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom_number]) }}">{{ $classroom->title }}</a>
@endsection

@section ('form')

    @can ('publish', [\App\Classroom::class, $classroom])
        <p class="text-center lead">This Classroom is currently <span class="text-danger">Unpublished</span>.</p>
        <div class="row justify-content-center">
           @include ('classroom.publish')
        </div>
    @endcan

    @can ('unpublish', [\App\Classroom::class, $classroom])
        <p class="text-center lead">This Classroom is currently <span class="text-secondary">Published</span>.</p>
        <div class="row justify-content-center">
           @include ('classroom.unpublish')
        </div>
    @endcan

    @cannot ('publish', [\App\Classroom::class, $classroom])
        @cannot ('unpublish', [\App\Classroom::class, $classroom])
            <p class="text-center lead text-warning ">You cannot publish this Classroom until a video is uploaded (see below).</p>
        @endcannot
    @endcannot

    @component ('components.form.master', ['method' => 'PATCH', 'form_action' => 'Update Classroom','url' => route('classroom.update', ['classroom' => $classroom->id]), 'csrf_token' => csrf_token()])

        @component ('components.form.input', ['name'=> 'title', 'type'=> 'text', 'errors' => $errors, 'value'=> $classroom->title])
            Title
        @endcomponent

        @component ('components.form.textarea', ['name'=> 'objective', 'errors' => $errors, 'max_characters' => \App\Classroom::getMaxObjectiveLength(), 'value'=> $classroom->objective])
            Objective
        @endcomponent

    @endcomponent

    <p class="text-center mt-2 mb-0 text-muted">Notes</p>
    <hr class="mt-0">

    @can ('uploadAttachment', [\App\Classroom::class, $classroom])
        <div class="row justify-content-center">
            @include ('classroom.upload-attachment')
        </div>
    @endcan

    @can ('deleteAttachment', [\App\Classroom::class, $classroom])
        <div class="row justify-content-center">
            @include ('classroom.delete-attachment')
        </div>
    @endcan

    <p class="text-center mt-2 mb-0 text-muted">Classroom Video</p>
    <hr class="mt-0">

    @can ('uploadVideo', [\App\Classroom::class, $classroom])
        <div class="row mb-3 justify-content-center">
            <a href="{{ route('classroom.uploadVideo', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom->number]) }}" class="btn btn-secondary text-white">Upload Video</a>
        </div>
    @endcan

    @can ('deleteVideo', [\App\Classroom::class, $classroom])
        <div class="row justify-content-center">
            @include ('classroom.delete-video')
        </div>
    @endcan

    <hr class="mt-2">
    
    @can ('delete', [\App\Classroom::class, $classroom])
        <div class="row justify-content-center">
            @include ('classroom.destroy')
        </div>
    @endcan

@endsection

resources/views/classroom/index.blade.php
<div class="list-classroom">
	@foreach ($lesson->classrooms as $index=>$classroom)
		@component ('components.classroom.card', ['lesson' => $lesson, 'classroom' => $classroom, 'index' => $index])
		@endcomponent
	@endforeach
</div>

resources/views/classroom/publish.blade.php
@component ('components.form.master', ['method' => 'POST', 'form_action' => 'Publish','url' => route('classroom.publish', ['classroom' => $classroom->id]), 'csrf_token' => csrf_token()])
@endcomponent

resources/views/classroom/show.blade.php
@extends ('layouts.app')

@section ('title')
	{{ $classroom->title }} - {{ $lesson->level }} {{ $lesson->subject }}, taught by {{ $lesson->user->name }}
@endsection

@section ('content')
	@if (isset($classroom->video))
		<div class="row no-gutters justify-content-center banner mb-3">
			<div class="col-xl-10">
				<div class="container-video">
					{!! $classroom->getVideoEmbed() !!}
				</div>
			</div>
		</div>
	@else
		@component('components.banner.large')
			<h3 class="text-center">{{ $lesson->user->name }} hasn't uploaded a video to this Classroom as yet.</h3>
		@endcomponent
	@endif

	<div class="row no-gutters justify-content-center meta-header-classroom">
		<div class="col-10">
			<div class="text-muted text-uppercase mb-2">
				<div class="row">
					<div class="col-12 col-sm-6">
						Classroom {{ $classroom_number }} • <span id="video-duration"></span> • 
						@if ($classroom->isPublished())
							<span class="text-secondary">Published {{ Carbon\Carbon::parse($classroom->publish_date)->diffForHumans() }}</span>
						@else
							<span class="text-danger">Unpublished</span>
						@endif
					</div>
					@if (isset($next_classroom))
						<div class="col-12 col-sm-6 next-classroom">
							<a href="{{ route('classroom.show', ['lesson' => $lesson->pretty_id, 'classroom_number' => $next_classroom->number]) }}">Next Classroom ></a>
						</div>
					@endif
				</div>
			</div>
		</div>
	</div>

	<div class="row no-gutters justify-content-center mb-3">
		<div class="col-10 col-lg-5">
			<h3><a href="{{ route('lesson.show', ['lesson' => $lesson->pretty_id]) }}">{{ $lesson->level }} {{ $lesson->subject }}</a></h3>
			<h3>
				{{ $classroom->title }}
				@can ('update', [\App\Classroom::class, $classroom])
					<a href="{{ route('classroom.edit', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom_number ]) }}" class="ion-gear-b text-secondary"></a>
				@endcan
			</h3>
			<p class="text-uppercase"><a href="{{ route('user.show', ['user' => $lesson->user->pretty_id])}}">{{ $lesson->user->name }}</a></p>
		</div>
		<div class="col-10 col-lg-5">
			<p class="text-muted">{{ $classroom->objective }}</p>
		</div>
	</div>

	<div class="row no-gutters justify-content-center text-center">
		<div class="col-sm-4 mb-3 text-nowrap"><a href="{{ route('quiz.index', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom_number]) }}" class="text-uppercase font-weight-light p-2 border border-secondary text-secondary"><i class="ion-flash"></i> Quizzes: {{ $classroom->quizzes->count() }}</a></div>
		<div class="col-sm-4 mb-3 text-nowrap"><a href="{{ route('assignment.index', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom_number]) }}" class="text-uppercase font-weight-light p-2 border border-secondary text-secondary"><i class="ion-link"></i> Assignments: {{ $classroom->assignments->count() }}</a></div>
		@if (isset($classroom->attachment))
			<div class="col-sm-4 mb-3 text-nowrap"><a href="{{ $classroom->attachment_download_path }}" class="text-uppercase font-weight-light p-2 border border-secondary text-secondary"> <i class="ion-ios-cloud-download"> </i> Notes</a></div>
		@endif
	</div>

	<div class="row no-gutters justify-content-center">
		<div class="col-10">
			@include('discussion.index')
		</div>
	</div>

@endsection

@section ('scripts')
	<script src="{{ asset('js/video.js') }}"></script>
@endsection

resources/views/classroom/unpublish.blade.php
@component ('components.form.master', ['method' => 'POST', 'form_action' => 'Unpublish','url' => route('classroom.unpublish', ['classroom' => $classroom->id]), 'csrf_token' => csrf_token()])
@endcomponent

resources/views/classroom/upload-attachment.blade.php
@component ('components.form.master', ['method' => 'POST', 'form_action' => 'Upload Notes','url' => route('classroom.storeAttachment', ['classroom' => $classroom->id]), 'enctype' => 'multipart/form-data', 'csrf_token' => csrf_token()])
	
	@component ('components.form.file', ['name'=> 'attachment'])
	    Notes (optional) - Word Document, PDF, Powerpoint, Zip etc.
	@endcomponent

@endcomponent

resources/views/classroom/upload-video.blade.php
@extends ('layouts.form')

@section ('title', 'Uploading Classroom Video')

@section ('subtitle')
	<a href="{{ route('classroom.show', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom_number]) }}">{{ $classroom->title }} - {{ $lesson->level }} {{ $lesson->subject }}</a>
@endsection

@section ('form')

    @component ('components.form.master',['method' => 'POST', 'form_action' => 'Upload Video','url' => $upload_link_secure, 'enctype' => 'multipart/form-data'])

        <input type="hidden" name="name" value="{{ $classroom->id }}">

        @component ('components.form.file', ['name'=> 'file_data'])
            Video File
        @endcomponent

    @endcomponent

@endsection