routes/web.php
Route::post('/users/{user}/payoff', 'UserController@payOff')
	->name('user.payOff');

Route::post('/users/{user}/upgrade', 'UserController@upgrade')
	->name('user.upgrade');

Route::post('/users/{user}/upgrade/cancel', 'UserController@cancelUpgrade')
	->name('user.cancelUpgrade');

Route::post('/users/{user}/downgrade', 'UserController@downgrade')
	->name('user.downgrade');

Route::post('/users/{user}/become-a-tutor-teacher', 'UserController@becomeATeacher')
	->name('user.becomeATeacher');

Route::post('/users/{user}/upgrade-to-teacher', 'UserController@upgradeToRegisteredTeacher')
	->name('user.upgradeToRegisteredTeacher');

Route::post('/users/{user}/photo', 'UserController@storePhoto')
	->name('user.storePhoto');

Route::post('/users/{user}/identification', 'UserController@storeIdentification')
	->name('user.storeIdentification');

Route::post('/users/{user}/qualifications', 'UserController@storeQualifications')
	->name('user.storeQualifications');

Route::post('/users/{user}/gift', 'UserController@gift')
	->name('user.gift');

Route::put('/users/{user}/photo', 'UserController@replacePhoto')
	->name('user.replacePhoto');

Route::delete('/users/{user}/photo', 'UserController@deletePhoto')
	->name('user.deletePhoto');

Route::delete('/users/{user}/identification', 'UserController@deleteIdentification')
	->name('user.deleteIdentification');

Route::delete('/users/{user}/qualifications', 'UserController@deleteQualifications')
	->name('user.deleteQualifications');

Route::delete('/users/{user}', 'UserController@destroy')
	->name('user.destroy');


// LESSONS
Route::get('/lessons', 'LessonController@index')
	->name('lesson.index');

Route::get('/lessons/create', 'LessonController@create')
	->name('lesson.create');

Route::get('/lessons/{lesson}', 'LessonController@show')
	->name('lesson.show');

Route::get('/lessons/{lesson}/edit', 'LessonController@edit')
	->name('lesson.edit');

Route::patch('/lessons/{lesson}', 'LessonController@update')
	->name('lesson.update');

Route::post('/lessons', 'LessonController@store')
	->name('lesson.store');

Route::post('/lessons/{lesson}/photo', 'LessonController@storePhoto')
	->name('lesson.storePhoto');

Route::post('/lessons/{lesson}/subscriptions/enable', 'LessonController@enableSubscriptions')
	->name('lesson.enableSubscriptions');

Route::post('/lessons/{lesson}/subscriptions/disable', 'LessonController@disableSubscriptions')
	->name('lesson.disableSubscriptions');

Route::put('/lessons/{lesson}/photo', 'LessonController@replacePhoto')
	->name('lesson.replacePhoto');

Route::delete('/lessons/{lesson}', 'LessonController@destroy')
	->name('lesson.destroy')
	->middleware($throttle_60);

Route::delete('/lessons/{lesson}/photo', 'LessonController@deletePhoto')
	->name('lesson.deletePhoto');


// CLASSROOMS
Route::get('/lessons/{lesson}/classrooms/create', 'ClassroomController@create')
	->name('classroom.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}', 'ClassroomController@show')
	->name('classroom.show');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/edit', 'ClassroomController@edit')
	->name('classroom.edit');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/video/upload', 'ClassroomController@uploadVideo')
	->name('classroom.uploadVideo')
	->middleware($throttle_15);

Route::get('/classrooms/{classroom}/video/uploaded', 'ClassroomController@uploadVideoComplete')
	->name('classroom.uploadVideoComplete');

Route::patch('/classrooms/{classroom}', 'ClassroomController@update')
	->name('classroom.update');

Route::post('/lessons/{lesson}/classrooms', 'ClassroomController@store')
	->name('classroom.store');

Route::post('/classrooms/{classroom}/attachment', 'ClassroomController@storeAttachment')
	->name('classroom.storeAttachment');

Route::post('/classrooms/{classroom}/publish', 'ClassroomController@publish')
	->name('classroom.publish');

Route::post('/classrooms/{classroom}/unpublish', 'ClassroomController@unpublish')
	->name('classroom.unpublish');

Route::delete('/classrooms/{classroom}', 'ClassroomController@destroy')
	->name('classroom.destroy')
	->middleware($throttle_15);

Route::delete('/classrooms/{classroom}/video', 'ClassroomController@deleteVideo')
	->name('classroom.deleteVideo')
	->middleware($throttle_15);

Route::delete('/classrooms/{classroom}/attachment', 'ClassroomController@deleteAttachment')
	->name('classroom.deleteAttachment');


// PROGRESS
Route::post('/classrooms/{classroom}/progresses', 'ProgressController@store')
	->name('progress.store');


// ASSIGNMENTS
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments', 'AssignmentController@index')
	->name('assignment.index');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments/create', 'AssignmentController@create')
	->name('assignment.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments/{assignment_number}/edit', 'AssignmentController@edit')
	->name('assignment.edit');

Route::patch('/assignment/{assignment}', 'AssignmentController@update')
	->name('assignment.update');

Route::post('/classrooms/{classroom}/assignments', 'AssignmentController@store')
	->name('assignment.store');

Route::delete('/assignment/{assignment}', 'AssignmentController@destroy')
	->name('assignment.destroy');


// QUIZZES
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes', 'QuizController@index')
	->name('quiz.index');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/create', 'QuizController@create')
	->name('quiz.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}', 'QuizController@show')
	->name('quiz.show');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/edit', 'QuizController@edit')
	->name('quiz.edit');

Route::patch('/quizzes/{quiz}', 'QuizController@update')
	->name('quiz.update');

Route::post('/classrooms/{classroom}/quizzes', 'QuizController@store')
	->name('quiz.store');

Route::delete('/quizzes/{quiz}', 'QuizController@destroy')
	->name('quiz.destroy');


// QUESTIONS
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/questions/create', 'QuestionController@create')
	->name('question.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/questions/{question_number}/edit', 'QuestionController@edit')
	->name('question.edit');

Route::patch('/questions/{question}', 'QuestionController@update')
	->name('question.update');

Route::post('/quizzes/{quiz}/questions', 'QuestionController@store')
	->name('question.store');

Route::post('/questions/{question}/photo', 'QuestionController@storePhoto')
	->name('question.storePhoto');

Route::put('/questions/{question}/photo', 'QuestionController@replacePhoto')
	->name('question.replacePhoto');

Route::delete('/questions/{question}', 'QuestionController@destroy')
	->name('question.destroy');

Route::delete('/questions/{question}/photo', 'QuestionController@deletePhoto')
	->name('question.deletePhoto');


// ANSWERS
Route::post('/quizzes/{quiz}/answers', 'AnswerController@store')
	->name('answer.store');


// DISCUSSIONS
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/discussions/create', 'DiscussionController@create')
	->name('discussion.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/discussions/{discussion_number}/edit', 'DiscussionController@edit')
	->name('discussion.edit');

Route::patch('/discussions/{discussion}', 'DiscussionController@update')
	->name('discussion.update');

Route::post('/classrooms/{classroom}/discussions', 'DiscussionController@store')
	->name('discussion.store');

Route::delete('/discussions/{discussion}', 'DiscussionController@destroy')
	->name('discussion.destroy');


// REVIEWS

Route::get('/lessons/{lesson}/reviews/create', 'ReviewController@create')
	->name('review.create');

Route::get('/lessons/{lesson}/reviews/{review_number}/edit', 'ReviewController@edit')
	->name('review.edit');

Route::patch('/reviews/{review}', 'ReviewController@update')
	->name('review.update');

Route::post('/lessons/{lesson}/reviews', 'ReviewController@store')
	->name('review.store');

Route::delete('/reviews/{review}', 'ReviewController@destroy')
	->name('review.destroy');


// SUBSCRIPTIONS, ORDERS AND PAYMENTS
Route::get('/lessons/{lesson}/subscribe', 'SubscriptionController@create')
	->name('subscription.create');

Route::get('/lessons/{lesson}/renew', 'SubscriptionController@createRenew')
	->name('subscription.createRenew');

Route::get('/lessons/{lesson}/subscribe-for-free', 'SubscriptionController@createFree')
	->name('subscription.createFree');

Route::get('/lessons/{lesson}/subscribe/pay', 'SubscriptionController@createOrder')
	->name('subscription.createOrder')
	->middleware($throttle_15);

Route::get('/lessons/{lesson}/renew/pay', 'SubscriptionController@createRenewOrder')
	->name('subscription.createRenewOrder')
	->middleware($throttle_15);

Route::get('/lessons/{lesson}/subscriptions', 'SubscriptionController@index')
	->name('subscription.index');

Route::get('/subscriptions/order/{subscription}', 'SubscriptionController@show')
	->name('subscription.show');

Route::get('/subscriptions/process/wipay', 'SubscriptionController@processWipayOrder')
	->name('subscription.processWipayOrder');

Route::get('/subscriptions/process/wipay-cash', 'SubscriptionController@processWipayCashOrder')
	->name('subscription.processWipayCashOrder');

Route::get('/subscriptions/renew/process/wipay', 'SubscriptionController@processWipayRenewOrder')
	->name('subscription.processWipayRenewOrder');

Route::get('/subscriptions/renew/process/wipay-cash', 'SubscriptionController@processWipayCashRenewOrder')
	->name('subscription.processWipayCashRenewOrder');

Route::post('/lessons/{lesson}/subscribe/free', 'SubscriptionController@storeFree')
	->name('subscription.storeFree');

Route::post('/subscriptions/{subscription}/refund', 'SubscriptionController@refund')

app/Discussion.php
<?php

namespace App;

class Discussion extends Model {

	const MAX_BODY_LENGTH = 280;

	// The attributes that are mass assignable.
	protected $fillable = [

	    'classroom_id', 'replyto', 'body'
	    
	];

	// The attributes that should be shown for arrays.
	protected $visible = [

	    'id', 'classroom_id', 'replyto', 'body'
	];

	public function user() {

		return $this->belongsTo(User::class);
		
	}

	public function classroom() {

	    return $this->belongsTo(Classroom::class);
	    
	}

	public function getNumberAttribute() {

	    $classroom = $this->classroom;

	    $results = $classroom->discussions->pluck('id')->search($this->id) + 1;

	    return $results ? $results : null;
	    
	}

	public function getChildDiscussionsAttribute() {

		return Discussion::where(['replyto' => $this->id])->get();

	}

	public function isRoot() {
		
		return $this->classroom->root_discussions->contains($this);

	}

	public static function getMaxBodyLength() {

		return self::MAX_BODY_LENGTH;

	}
    
}

app/Lesson.php
<?php

namespace App;

use App\Defaults\Subject;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Laravel\Scout\Searchable;

class Lesson extends Model {

	use Searchable;

	const MAX_DESCRIPTION_LENGTH = 280;

	public $asYouType = true;

	// The attributes that are mass assignable.
	protected $fillable = [

	    'photo', 'subject', 'level', 'price', 'description', 'last_publish_date', 'subscriptions_disabled', 'marked_for_deletion'
	    
	];

	// The attributes that should be shown for arrays.
	protected $visible = [

	    'id', 'photo', 'subject', 'level', 'price', 'description', 'last_publish_date', 'subscriptions_disabled', 'marked_for_deletion'

	];

	public function __construct(array $attributes = array(), $photo = null) {

        // Eloquent
		parent::__construct($attributes);

		if (isset($photo)) {

			$this->photo = self::savePhoto($photo);

		}

	}

	public function user() {

	    return $this->belongsTo(User::class);

	}

	public function classrooms() {

	    return $this->hasMany(Classroom::class);

	}

	public function reviews() {

		return $this->hasMany(Review::class);

	}

	public function subscriptions() {

	    return $this->hasMany(Subscription::class);

	}

	public function getActiveSubscriptionsCountAttribute() {

		$count = 0;

		$this->subscriptions->each(function($subscription) use (&$count) {
			if ($subscription->isActive()) {
				$count++;
			}
		});

		return $count;
		
	}

	public function getPrettyIDAttribute() {

		$id = str_replace(" ", "-", $this->id);
		$level = str_replace(" ", "-", $this->level);
		$subject = str_replace(" ", "-", $this->subject); 
		$teacher_name = str_replace(" ", "-", $this->user->name);

		return "$id-$level-$subject-$teacher_name";

	}

	public function getUnwatchedClassroomsAttribute() {
		
		$count = 0;

		$this->classrooms->each(function($classroom) use (&$count){
            
			if (!$classroom->progress_completed && $classroom->isPublished()) {
				$count++;
			}

        });

		return $count;

	}

	public function getRatingAttribute() {

		$avg = $this->reviews->avg('rating');

		return $this->reviews->isNotEmpty() ?  round($avg) : 0;

	}

	public function getPhotoUrlAttribute() {

		if (isset($this->photo)) {

			return Storage::disk('spaces')->url($this->photo);

		}
		return (resolve(Subject::class))->getPhotoUrl($this->subject);

	}

	/**
	 * Get the indexable data array for the model.
	 *
	 * @return array
	 */
	public function toSearchableArray() {

	    $array = $this->toArray();

	    return [
	    	'id' => $array['id'],
	    	'subject' => $array['subject'],
	    	'level' => $array['level'],
	    	'description' => $array['description'],
	    ];

	}

	public function getClassroomByNumber($classroom_number) {

		if ($classroom = $this->classrooms->get($classroom_number - 1)) {
			return $classroom;
		}
		
		abort(404, 'Classroom not found.');

	}

	public function getReviewByNumber($review_number) {

		if ($review = $this->reviews->get($review_number - 1)) {
			return $review;
		}

		abort(404, 'Review not found.');
	}

	public function addClassroom(Classroom $classroom) {

		return $this->classrooms()->save($classroom);

	}

	public function deletePhoto() {

		if (isset($this->photo)) {

			Storage::disk('spaces')->delete($this->photo);

			$this->update([
			    'photo' => null
			]);

		}

		return $this;
		
	}

	public function uploadPhoto($photo) {
		
		$photo_uri =  self::savePhoto($photo);

		$this->update([
		    'photo' => $photo_uri
		]);

	}

	public function updateLatestPublishDate() {
		
		$last_publish_date = $this->created_at;
		$classrooms = $this->classrooms;

		$classrooms->each(function($classroom) use (&$last_publish_date) {
			if ($classroom->isPublished()) {
				if (Carbon::parse($classroom->publish_date)->gt(Carbon::parse($last_publish_date))) {
					$last_publish_date = $classroom->publish_date;
				}
			}
		});

		$this->update([
			'last_publish_date' => Carbon::parse($last_publish_date)
		]);

		return $last_publish_date;

	}

	public function getNextClassroom($classroom_number) {

		$classrooms = $this->classrooms;
		$next_classroom = null;

		$classrooms->each(function($classroom, $key) use(&$classroom_number, &$next_classroom) {
			$number = $key + 1;
			if (($number > $classroom_number) && ($classroom->isPublished())) {
				$next_classroom = $classroom;
				return false;
			}
		});

		return $next_classroom;
		
	}

	public function isSubscriptionsDisabled() {
		
		return $this->subscriptions_disabled === 1;

	}

	public function enableSubscriptions() {
		
		$this->update([
			'subscriptions_disabled' => 0
		]);

		return $this;

	}

	public function disableSubscriptions() {
		
		$this->update([
			'subscriptions_disabled' => 1
		]);

		return $this;

	}

	public static function getMaxDescriptionLength() {

		return self::MAX_DESCRIPTION_LENGTH;

	}

	private static function savePhoto($photo) {

		$path = 'uploads/lessons/photos/'.$photo->hashName();
		$img = Image::make($photo)->fit(1920, 1080)->encode();
		
		return Storage::disk('spaces')->put($path, (string) $img, 'public') ? $path : null;

	}
	
}

resources/views/discussion/create.blade.php
@extends ('layouts.form')

@section ('title', 'Writing a Comment')

@section ('subtitle')
    <a href="{{ route('classroom.show', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom->number]) }}">
    {{ $classroom->title }} - {{ $lesson->level }} {{ $lesson->subject }}</a>
@endsection

@section ('form')
	
	@if (isset($replyto))
		<p class="mb-2 lead text-muted">Replying to:</p>
		<div class="card">
			<div class="card-body">
			  <div class="mb-1">
			  	<a href="{{ route('user.show', ['user' => $replyto->user->pretty_id]) }}">
			  	    {{ $replyto->user->name }}
			  	</a>
			  	<span class="text-muted">
			  		•
			  		<small>{{ $replyto->created_at->diffForHumans() }}</small>
			  	</span>
			  </div>
			  <p class="mb-1">{{ $replyto->body }}</p>
			</div>
		</div>
		<hr>
	@endif

    @component ('components.form.master', ['method' => 'POST', 'form_action' => 'Post Comment','url' => route('discussion.store', ['classroom' => $classroom->id]), 'csrf_token' => csrf_token()])

        @component ('components.form.textarea', ['name'=> 'body', 'errors' => $errors, 'max_characters' => \App\Discussion::getMaxBodyLength(), 'value'=> old('body')])
            Comment
        @endcomponent

        @if (isset($replyto))
			<input type="hidden" name="replyto" value="{{ $replyto->id }}">
		@endif

    @endcomponent

@endsection

resources/views/discussion/destroy.blade.php
@component ('components.form.master', ['method' => 'DELETE', 'form_action' => 'Delete Discussion', 'btn_class' => 'btn-danger','url' => route('discussion.destroy', ['discussion' => $discussion->id]), 'csrf_token' => csrf_token()])
@endcomponent

resources/views/discussion/edit.blade.php
@extends ('layouts.form')

@section ('title', 'Updating your Discussion')

@section ('subtitle')
    <a href="{{ route('classroom.show', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom->number]) }}">
    {{ $classroom->title }} - {{ $lesson->level }} {{ $lesson->subject }}</a>
@endsection

@section ('form')

    @component ('components.form.master', ['method' => 'PATCH', 'form_action' => 'Update Discussion','url' => route('discussion.update', ['discussion' => $discussion->id]), 'csrf_token' => csrf_token()])

        @component ('components.form.textarea', ['name'=> 'body', 'errors' => $errors, 'max_characters' => \App\Discussion::getMaxBodyLength(), 'value'=> $discussion->body])
            Body
        @endcomponent

    @endcomponent

    <hr>

	@can ('delete', [\App\Discussion::class, $discussion])
		<div class="row mb-3 justify-content-center">
	    	@include ('discussion.destroy')
	    </div>
	@endcan

@endsection

resources/views/discussion/index.blade.php
@if($classroom->discussions->count() > 0)
	<hr>
	<div class="text-center">
		<h3>Latest Discussions</h3>
	</div>
	<div class="row justify-content-center">
		<div class="col-8">
			@foreach ($root_discussions as $index=>$discussion)
				<div class="mb-3">
					@component('components.discussion.comment', ['discussion' => $discussion, 'discussion_number'=> ($index + 1), 'classroom' => $classroom, 'lesson' => $lesson])
					@endcomponent
					@can('create', [\App\Discussion::class, $classroom])
						<small><a href="{{ route('discussion.create', ['lesson' => $lesson->pretty_id, 'classroom' => $classroom->number, 'replyto' => $discussion->id]) }}">Reply</a></small>
					@endcan
					<div class="ml-5">
						@foreach ($discussion->child_discussions as $child_index=>$child_discussion)
							@component('components.discussion.comment', ['discussion' => $child_discussion, 'discussion_number'=> $discussion->number, 'classroom' => $classroom, 'lesson' => $lesson])
							@endcomponent
						@endforeach
					</div>
				</div>
			@endforeach
		</div>
	</div>
@endif

<div class="text-center">
	@can('create', [\App\Discussion::class, $classroom])
		<a href="{{ route('discussion.create', ['lesson' => $lesson->pretty_id, 'classroom' => $classroom->number]) }}" class="btn btn-secondary text-white">New Comment</a>
	@endcan
</div>

<div class="row justify-content-center pt-2">

	{{ $root_discussions->links() }}

</div>