routes/web.php
Route::post('/users/{user}/payoff', 'UserController@payOff')
	->name('user.payOff');

Route::post('/users/{user}/upgrade', 'UserController@upgrade')
	->name('user.upgrade');

Route::post('/users/{user}/upgrade/cancel', 'UserController@cancelUpgrade')
	->name('user.cancelUpgrade');

Route::post('/users/{user}/downgrade', 'UserController@downgrade')
	->name('user.downgrade');

Route::post('/users/{user}/become-a-tutor-teacher', 'UserController@becomeATeacher')
	->name('user.becomeATeacher');

Route::post('/users/{user}/upgrade-to-teacher', 'UserController@upgradeToRegisteredTeacher')
	->name('user.upgradeToRegisteredTeacher');

Route::post('/users/{user}/photo', 'UserController@storePhoto')
	->name('user.storePhoto');

Route::post('/users/{user}/identification', 'UserController@storeIdentification')
	->name('user.storeIdentification');

Route::post('/users/{user}/qualifications', 'UserController@storeQualifications')
	->name('user.storeQualifications');

Route::post('/users/{user}/gift', 'UserController@gift')
	->name('user.gift');

Route::put('/users/{user}/photo', 'UserController@replacePhoto')
	->name('user.replacePhoto');

Route::delete('/users/{user}/photo', 'UserController@deletePhoto')
	->name('user.deletePhoto');

Route::delete('/users/{user}/identification', 'UserController@deleteIdentification')
	->name('user.deleteIdentification');

Route::delete('/users/{user}/qualifications', 'UserController@deleteQualifications')
	->name('user.deleteQualifications');

Route::delete('/users/{user}', 'UserController@destroy')
	->name('user.destroy');


// LESSONS
Route::get('/lessons', 'LessonController@index')
	->name('lesson.index');

Route::get('/lessons/create', 'LessonController@create')
	->name('lesson.create');

Route::get('/lessons/{lesson}', 'LessonController@show')
	->name('lesson.show');

Route::get('/lessons/{lesson}/edit', 'LessonController@edit')
	->name('lesson.edit');

Route::patch('/lessons/{lesson}', 'LessonController@update')
	->name('lesson.update');

Route::post('/lessons', 'LessonController@store')
	->name('lesson.store');

Route::post('/lessons/{lesson}/photo', 'LessonController@storePhoto')
	->name('lesson.storePhoto');

Route::post('/lessons/{lesson}/subscriptions/enable', 'LessonController@enableSubscriptions')
	->name('lesson.enableSubscriptions');

Route::post('/lessons/{lesson}/subscriptions/disable', 'LessonController@disableSubscriptions')
	->name('lesson.disableSubscriptions');

Route::put('/lessons/{lesson}/photo', 'LessonController@replacePhoto')
	->name('lesson.replacePhoto');

Route::delete('/lessons/{lesson}', 'LessonController@destroy')
	->name('lesson.destroy')
	->middleware($throttle_60);

Route::delete('/lessons/{lesson}/photo', 'LessonController@deletePhoto')
	->name('lesson.deletePhoto');


// CLASSROOMS
Route::get('/lessons/{lesson}/classrooms/create', 'ClassroomController@create')
	->name('classroom.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}', 'ClassroomController@show')
	->name('classroom.show');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/edit', 'ClassroomController@edit')
	->name('classroom.edit');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/video/upload', 'ClassroomController@uploadVideo')
	->name('classroom.uploadVideo')
	->middleware($throttle_15);

Route::get('/classrooms/{classroom}/video/uploaded', 'ClassroomController@uploadVideoComplete')
	->name('classroom.uploadVideoComplete');

Route::patch('/classrooms/{classroom}', 'ClassroomController@update')
	->name('classroom.update');

Route::post('/lessons/{lesson}/classrooms', 'ClassroomController@store')
	->name('classroom.store');

Route::post('/classrooms/{classroom}/attachment', 'ClassroomController@storeAttachment')
	->name('classroom.storeAttachment');

Route::post('/classrooms/{classroom}/publish', 'ClassroomController@publish')
	->name('classroom.publish');

Route::post('/classrooms/{classroom}/unpublish', 'ClassroomController@unpublish')
	->name('classroom.unpublish');

Route::delete('/classrooms/{classroom}', 'ClassroomController@destroy')
	->name('classroom.destroy')
	->middleware($throttle_15);

Route::delete('/classrooms/{classroom}/video', 'ClassroomController@deleteVideo')
	->name('classroom.deleteVideo')
	->middleware($throttle_15);

Route::delete('/classrooms/{classroom}/attachment', 'ClassroomController@deleteAttachment')
	->name('classroom.deleteAttachment');


// PROGRESS
Route::post('/classrooms/{classroom}/progresses', 'ProgressController@store')
	->name('progress.store');


// ASSIGNMENTS
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments', 'AssignmentController@index')
	->name('assignment.index');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments/create', 'AssignmentController@create')
	->name('assignment.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/assignments/{assignment_number}/edit', 'AssignmentController@edit')
	->name('assignment.edit');

Route::patch('/assignment/{assignment}', 'AssignmentController@update')
	->name('assignment.update');

Route::post('/classrooms/{classroom}/assignments', 'AssignmentController@store')
	->name('assignment.store');

Route::delete('/assignment/{assignment}', 'AssignmentController@destroy')
	->name('assignment.destroy');


// QUIZZES
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes', 'QuizController@index')
	->name('quiz.index');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/create', 'QuizController@create')
	->name('quiz.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}', 'QuizController@show')
	->name('quiz.show');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/edit', 'QuizController@edit')
	->name('quiz.edit');

Route::patch('/quizzes/{quiz}', 'QuizController@update')
	->name('quiz.update');

Route::post('/classrooms/{classroom}/quizzes', 'QuizController@store')
	->name('quiz.store');

Route::delete('/quizzes/{quiz}', 'QuizController@destroy')
	->name('quiz.destroy');


// QUESTIONS
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/questions/create', 'QuestionController@create')
	->name('question.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/quizzes/{quiz_number}/questions/{question_number}/edit', 'QuestionController@edit')
	->name('question.edit');

Route::patch('/questions/{question}', 'QuestionController@update')
	->name('question.update');

Route::post('/quizzes/{quiz}/questions', 'QuestionController@store')
	->name('question.store');

Route::post('/questions/{question}/photo', 'QuestionController@storePhoto')
	->name('question.storePhoto');

Route::put('/questions/{question}/photo', 'QuestionController@replacePhoto')
	->name('question.replacePhoto');

Route::delete('/questions/{question}', 'QuestionController@destroy')
	->name('question.destroy');

Route::delete('/questions/{question}/photo', 'QuestionController@deletePhoto')
	->name('question.deletePhoto');


// ANSWERS
Route::post('/quizzes/{quiz}/answers', 'AnswerController@store')
	->name('answer.store');


// DISCUSSIONS
Route::get('/lessons/{lesson}/classrooms/{classroom_number}/discussions/create', 'DiscussionController@create')
	->name('discussion.create');

Route::get('/lessons/{lesson}/classrooms/{classroom_number}/discussions/{discussion_number}/edit', 'DiscussionController@edit')
	->name('discussion.edit');

Route::patch('/discussions/{discussion}', 'DiscussionController@update')
	->name('discussion.update');

Route::post('/classrooms/{classroom}/discussions', 'DiscussionController@store')
	->name('discussion.store');

Route::delete('/discussions/{discussion}', 'DiscussionController@destroy')
	->name('discussion.destroy');


// REVIEWS

Route::get('/lessons/{lesson}/reviews/create', 'ReviewController@create')
	->name('review.create');

Route::get('/lessons/{lesson}/reviews/{review_number}/edit', 'ReviewController@edit')
	->name('review.edit');

Route::patch('/reviews/{review}', 'ReviewController@update')
	->name('review.update');

Route::post('/lessons/{lesson}/reviews', 'ReviewController@store')
	->name('review.store');

Route::delete('/reviews/{review}', 'ReviewController@destroy')
	->name('review.destroy');


// SUBSCRIPTIONS, ORDERS AND PAYMENTS
Route::get('/lessons/{lesson}/subscribe', 'SubscriptionController@create')
	->name('subscription.create');

Route::get('/lessons/{lesson}/renew', 'SubscriptionController@createRenew')
	->name('subscription.createRenew');

Route::get('/lessons/{lesson}/subscribe-for-free', 'SubscriptionController@createFree')
	->name('subscription.createFree');

Route::get('/lessons/{lesson}/subscribe/pay', 'SubscriptionController@createOrder')
	->name('subscription.createOrder')
	->middleware($throttle_15);

Route::get('/lessons/{lesson}/renew/pay', 'SubscriptionController@createRenewOrder')
	->name('subscription.createRenewOrder')
	->middleware($throttle_15);

Route::get('/lessons/{lesson}/subscriptions', 'SubscriptionController@index')
	->name('subscription.index');

Route::get('/subscriptions/order/{subscription}', 'SubscriptionController@show')
	->name('subscription.show');

Route::get('/subscriptions/process/wipay', 'SubscriptionController@processWipayOrder')
	->name('subscription.processWipayOrder');

Route::get('/subscriptions/process/wipay-cash', 'SubscriptionController@processWipayCashOrder')
	->name('subscription.processWipayCashOrder');

Route::get('/subscriptions/renew/process/wipay', 'SubscriptionController@processWipayRenewOrder')
	->name('subscription.processWipayRenewOrder');

Route::get('/subscriptions/renew/process/wipay-cash', 'SubscriptionController@processWipayCashRenewOrder')
	->name('subscription.processWipayCashRenewOrder');

Route::post('/lessons/{lesson}/subscribe/free', 'SubscriptionController@storeFree')
	->name('subscription.storeFree');

Route::post('/subscriptions/{subscription}/refund', 'SubscriptionController@refund')

app/Assignment.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;

class Assignment extends Model {

	const MAX_INSTRUCTIONS_LENGTH = 280;

	// The attributes that are mass assignable.
	protected $fillable = [

	    'classroom_id', 'title', 'instructions', 'questions', 'solutions', 'solutions_release_days'
	    
	];

	// The attributes that should be shown for arrays.
	protected $visible = [

	    'id', 'classroom_id', 'title', 'instructions', 'questions', 'solutions', 'solutions_release_days'

	];

	public function __construct(array $attributes = array(), $questions = null, $solutions = null) {

        // Eloquent
		parent::__construct($attributes);

		if (!isset($this->solutions_release_days) || !(isset($solutions))) {

			$this->solutions_release_days = 0;
			
		}

		if (isset($questions)) {

			$this->questions = self::saveQuestions($questions);

		}

		if (isset($solutions)) {

			$this->solutions = self::saveSolutions($solutions);

		}

	}

	public function user() {

		return $this->belongsTo(User::class);
		
	}
    
	public function classroom() {

	    return $this->belongsTo(Classroom::class);
	    
	}

	public function getNumberAttribute() {

	    $classroom = $this->classroom;

	    $results = $classroom->assignments->pluck('id')->search($this->id) + 1;

	    return $results ? $results : null;
	    
	}

	public function getQuestionsDownloadPathAttribute() {

		return env('SPACES_URL').'/'.$this->questions;

	}

	public function getSolutionsDownloadPathAttribute() {

		return env('SPACES_URL').'/'.$this->solutions;

	}

	public function getSolutionsReleaseDateAttribute() {
		
		if (isset($this->classroom->publish_date)) {

			$publish_date = Carbon::parse($this->classroom->publish_date);
			$release_date = $publish_date->addDays($this->solutions_release_days);
			return $release_date;

		}

		return null;

	}

	public function getIsSolutionsReleasedAttribute() {

		$now = Carbon::now();
		$release_date = $this->solutions_release_date;

		if (isset($release_date)) {

			return $release_date->lte($now);

		}

		return false;

	}

	public function deleteQuestions() {

		if (isset($this->questions)) {

			Storage::disk('spaces')->delete($this->questions);

			$this->update([
			    'questions' => null
			]);

		}

		return $this;

	}


	public function deleteSolutions() {

		if (isset($this->solutions)) {

			Storage::disk('spaces')->delete($this->solutions);

			$this->update([
			    'solutions' => null,
			    'solutions_release_days' => 0
			]);

		}

		return $this;

	}


	public static function getMaxInstructionsLength() {

		return self::MAX_INSTRUCTIONS_LENGTH;

	}

	private static function saveQuestions($questions) {

		$location = 'uploads/assignments/questions';
		$path = $location.'/'.$questions->hashName();

		return Storage::disk('spaces')->putFile($location, $questions, 'public') ? $path : null;

	}

	private static function saveSolutions($solutions) {

		$location = 'uploads/assignments/solutions';
		$path = $location.'/'.$solutions->hashName();

		return Storage::disk('spaces')->putFile($location, $solutions, 'public') ? $path : null;

	}
    
}

app/Http/Controllers/AssignmentController.php
<?php

namespace App\Http\Controllers;

use App\Assignment;
use App\Classroom;
use App\Lesson;
use Illuminate\Http\Request;
use JavaScript;

class AssignmentController extends Controller {
    
	public function __construct() {
	    
	    $this->middleware('auth');
	    
	}

	public function index(Lesson $lesson, $classroom_number) {

		$classroom = $lesson->getClassroomByNumber($classroom_number);

		$this->authorize('index', [Assignment::class, $classroom]);
	    
	    return view('assignment.index', compact('lesson', 'classroom', 'classroom_number'));
	    
	}

	public function create(Lesson $lesson, $classroom_number) {

		$classroom = $lesson->getClassroomByNumber($classroom_number);

	    $this->authorize('create', [Assignment::class, $classroom]);

	    return view('assignment.create', compact('lesson', 'classroom', 'classroom_number'));

	}

	public function store(Classroom $classroom) {

	    $this->authorize('create', [Assignment::class, $classroom]);

	    $lesson = $classroom->lesson;

	    $assignment_data = request()->validate([
	            'questions' => 'file|max:25000|mimes:doc,docx,pdf,txt,rtf,jpg,jpeg,bmp,png,zip',
	            'solutions' => 'file|max:25000|mimes:doc,docx,pdf,txt,rtf,jpg,jpeg,bmp,png,zip',
	            'solutions_release_days' => 'nullable|integer|min:0',
	            'title' => 'required|max:30|profane:'.resource_path('lang/en/profane_local.php'),
	            'instructions' => 'required|max:'.Assignment::getMaxInstructionsLength().'|profane:'.resource_path('lang/en/profane_local.php'),
	        ]);

	    $assignment = $classroom->addAssignment(new Assignment($assignment_data, request()->questions, request()->solutions));

	    // Alert user that assignment has been created.
	    alert()->success('Your assignment has been created.', 'Assignment created');

	    return redirect()->route('assignment.index', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom->number]);

	}

	public function edit(Lesson $lesson, $classroom_number, $assignment_number) {

	    $classroom = $lesson->getClassroomByNumber($classroom_number);
	    $assignment = $classroom->getAssignmentByNumber($assignment_number);

	    $this->authorize('update', [Assignment::class, $assignment]);

	    JavaScript::put(['forms' => [

	    	[
	    	'id' => 'delete-assignment',
	    	'swal_submit' => [
	    	    'title' => 'Deleting Assignment',
	    	    'text' => 'Are you sure you\'d like to delete this Assignment?',
	    	    'icon' => 'warning',
	    	    'danger' => true,
	    	    ]
	    	]

	    ]]);

	    return view('assignment.edit', compact('lesson', 'classroom', 'assignment', 'classroom_number', 'assignment_number'));
	    
	}

	public function update(Assignment $assignment) {

	    $this->authorize('update', [Assignment::class, $assignment]);

	    $classroom = $assignment->classroom;
	    $lesson = $classroom->lesson;

	    $assignment_data = request()->validate([
	    	'title' => 'required|max:30|profane:'.resource_path('lang/en/profane_local.php'),
	    	'instructions' => 'required|max:'.Assignment::getMaxInstructionsLength().'|profane:'.resource_path('lang/en/profane_local.php'),
	    	'solutions_release_days' => 'nullable|integer|min:0',
	    ]);

	    if ($assignment_data['solutions_release_days'] === null) {
	    	$assignment_data['solutions_release_days'] = 0;
	    }

	    $assignment->update($assignment_data);

	    alert()->success('Your assignment has been updated.', 'Assignment Updated');

	    return redirect()->route('assignment.index', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom->number]);

	}

	public function destroy(Assignment $assignment) {

		$this->authorize('delete', [Assignment::class, $assignment]);

		$classroom = $assignment->classroom;
		$lesson = $classroom->lesson;

	    $assignment->delete();

	    alert()->success('Your assignment has been deleted.', 'Assignment Deleted');

	    return redirect()->route('assignment.index', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom->number]);

	}

}

resources/views/assignment/create.blade.php
@extends ('layouts.form')

@section ('title', 'Creating Assignment')

@section ('subtitle')
	<a href="{{ route('classroom.show', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom_number]) }}">
	    {{ $classroom->title }} - {{ $lesson->level }} {{ $lesson->subject }}</a>
@endsection

@section ('form')

    @component ('components.form.master', ['method' => 'POST', 'form_action' => 'Create Assignment','url' => route('assignment.store', ['classroom' => $classroom->id]), 'enctype' => 'multipart/form-data', 'csrf_token' => csrf_token()])

        @component ('components.form.input', ['name'=> 'title', 'type'=> 'text', 'errors' => $errors, 'value'=> old('title')])
            Title
        @endcomponent

        @component ('components.form.textarea', ['name'=> 'instructions', 'errors' => $errors, 'max_characters' => \App\Assignment::getMaxInstructionsLength(), 'value'=> old('instructions')])
            Instructions
        @endcomponent

        <hr>

        @component ('components.form.file', ['name'=> 'questions', 'errors' => $errors, 'not_required' => true])
            Question Sheet (optional)
        @endcomponent
        
        <hr>
        
        @component ('components.form.file', ['name'=> 'solutions', 'errors' => $errors, 'not_required' => true])
            Solution Sheet (optional)
        @endcomponent

        <p class="text-center">Your Solutions can be released in the future. Please enter the number of days we should wait before releasing the Solutions (We start counting from the day you Publish this Classroom). Leave Blank for IMMEDIATE release.</p>        

        @component ('components.form.input', ['name'=> 'solutions_release_days', 'type'=> 'text', 'errors' => $errors, 'value'=> old('solutions_release_days'), 'not_required' => true])
            Number of Days
        @endcomponent
    
    @endcomponent

@endsection

resources/views/assignment/destroy.blade.php
@component ('components.form.master', ['method' => 'DELETE', 'form_action' => 'Delete Assignment', 'btn_class' => 'btn-danger', 'url' => route('assignment.destroy', ['assignment' => $assignment->id]), 'csrf_token' => csrf_token()])
@endcomponent

resources/views/assignment/edit.blade.php
@extends ('layouts.form')

@section ('title', 'Updating Assignment')

@section ('subtitle')
	<a href="{{ route('classroom.show', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom_number]) }}">
	    {{ $classroom->title }} - {{ $lesson->level }} {{ $lesson->subject }}</a>
@endsection

@section ('form')

    @component ('components.form.master', ['method' => 'PATCH', 'form_action' => 'Update Assignment','url' => route('assignment.update', ['assignment' => $assignment->id]), 'enctype' => 'multipart/form-data', 'csrf_token' => csrf_token()])

        @component ('components.form.input', ['name'=> 'title', 'type'=> 'text', 'errors' => $errors, 'value'=> $assignment->title])
            Title
        @endcomponent

        @component ('components.form.textarea', ['name'=> 'instructions', 'errors' => $errors, 'max_characters' => \App\Assignment::getMaxInstructionsLength(), 'value'=> $assignment->instructions])
            Instructions
        @endcomponent
        
        @if (isset($assignment->solutions_release_days))
            <hr>
            <p class="text-center">Your Solutions can be released in the future. Please enter the number of days we should wait before releasing the Solutions (We start counting from the day you Publish this Classroom). Leave Blank for IMMEDIATE release.</p> 
            @component ('components.form.input', ['name'=> 'solutions_release_days', 'type'=> 'text', 'errors' => $errors, 'value'=> $assignment->solutions_release_days, 'not_required' => true])
                Number of Days
            @endcomponent
        @endif

    @endcomponent

    <hr>

    <div class="text-center mb-3">
        <h3>Assignment Files</h3>
    </div>

    <div class="row mb-3">
        @if (isset($assignment->questions))
            <div class="col-6">
                <p class="card-text">Questions: <a href="{{ $assignment->questions_download_path }}" class="text-uppercase font-weight-light text-secondary"> <i class="ion-ios-cloud-download"> </i>Download</a></p>
            </div>
        @endif
        @if (isset($assignment->solutions))
            <div class="col-6">
                <p class="card-text">Solutions: <a href="{{ $assignment->solutions_download_path }}" class="text-uppercase font-weight-light text-secondary"> <i class="ion-ios-cloud-download"> </i>Download</a></p>
            </div>
        @endif
    </div>
    
    @if (isset($assignment->solutions_release_days))
        @if ($assignment->solutions_release_days > 0)
            <p class="card-text text-center">Solutions will be released {{ $assignment->solutions_release_days }} days after you publish this Classroom.</p>
        @else
            <p class="card-text text-center">Solutions will be released immediately after you publish this Classroom.</p>
        @endif
    @endif

    <hr>

    @can ('delete', [\App\Assignment::class, $assignment])
        <div class="row mb-3 justify-content-center">
            @include ('assignment.destroy')
        </div>
    @endcan 

@endsection

resources/views/assignment/index.blade.php
@extends ('layouts.app')

@section ('title')
	Assignments - {{ $classroom->title }} - {{ $lesson->level }} {{ $lesson->subject }}, taught by {{ $lesson->user->name }}
@endsection

@section ('content')

	@component('components.banner.small')
	    <h2>Assignments</h2>

	    <small><a href="{{ route('classroom.show', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom_number]) }}">
	        {{ $classroom->title }} - {{ $lesson->level }} {{ $lesson->subject }}
	    </a></small>
	@endcomponent

	@if ($classroom->assignments->count() < 1)
		<div class="container p-5">
			<h3 class="text-center">{{ $lesson->user->name }} hasn't uploaded an Assignment to this Classroom.</h3>
		</div>
	@endif

	<div class="container">
		@foreach ($classroom->assignments as $index=>$assignment)
			@component ('components.assignment.card', ['lesson' => $lesson, 'classroom' => $classroom, 'assignment' => $assignment, 'classroom_number' => $classroom_number, 'index' => $index])
			@endcomponent
		@endforeach
		@can ('create', [\App\Assignment::class, $classroom])
			<div class="row justify-content-center">
				<a href="{{ route('assignment.create', ['lesson' => $lesson->pretty_id, 'classroom_number' => $classroom_number]) }}" class="btn btn-secondary text-white">Create Assignment</a>
			</div>
		@endcan
	</div>


@endsection